### ISSUE TITLE
Make a Title Screen 

### ISSUE THREAD

**Issue by sdrhoads** [UCSB-CS56-Projects/cs56-games-country-runner#12]
An opening screen that has (some) of the following options: 

Play Game
Help (How to Play)
High Scores (Or list High Scores directly on Title Page)

Play Game is most important followed by the Help Screen.  High Scores cannot be implemented until a scoring system exists so it may be a issue for the future. 

@andrewberls
~estimated 200

**Comment by jalexanderqed** [comment]
F16 CLOSED: A title screen has been added.
