### ISSUE TITLE
Fix Collision Detection

### ISSUE THREAD

**Issue by sdrhoads** [UCSB-CS56-Projects/cs56-games-country-runner#13]
Current collision detection is kind of buggy.  It only check if the objects are at the exact same x and y position (so if the edge of the sprite clearly touches the obstacle, the game doesn't register it as a collision.) 

We will need to know the size of each obstacle and the runner in order to have a more accurate collision detection.  

@andrewberls
~estimated 150

**Comment by jalexanderqed** [comment]
F16 CLOSED: Collision detection has been fixed.
