### ISSUE TITLE
Add More Obstacles

### ISSUE THREAD

**Issue by sdrhoads** [UCSB-CS56-Projects/cs56-games-country-runner#15]
Create some different obstacles.  They can differ in size or speed so that the player has to vary his tactics.  This will make the game more interesting! Later, if we want to vary the game by time or levels, different obstacles can help us control how difficult the game is.

@andrewberls
~estimated 200

**Comment by jalexanderqed** [comment]
F16 CLOSED: Additional obstacles have been added.
