### ISSUE TITLE
Draw our own Pixel Sprites and assemble into a spritesheet

### ISSUE THREAD

**Issue by sdrhoads** [UCSB-CS56-Projects/cs56-games-country-runner#16]
Because we are implementing sprite sheets now, we will have to draw our own pixel sprites. (We are testing with random mismatching images right now) 
 
Sprites should be contained within 100 X 100 pixels. 

Sprites we intend to make include 
Runner: poses for running
Runner: jumping (upward motion pose and falling pose)
Sheep Obstacle: Running poses
Scarecrow Obstacle: (He is stationary so no poses)

If time permits we can add:
Runner: Dying poses
Bird Obstacle: flying poses
New Obstacles

If even more time permits we can add:
Runner: Collision poses
Obstacle Collision poses 
More New Obstacles 

@andrewberls

**Comment by jalexanderqed** [comment]
F16 CLOSED: Currently, the images being used are from the Internet and drawing new ones would probably be a waste of time. Additional animations would be nice but should probably not be added at this point.
