### ISSUE TITLE
Fix the window positioning

### ISSUE THREAD

**Issue by thetomcraig** [UCSB-CS56-Projects/cs56-games-country-runner#20]
The game window is set to a specific resolution in the CountryRunnerGui class.  This is fine, but the JPanel is not made to match the JFrame size automatically.  As such, the screen can be resized and this causes the game to continue running when it should not.  Perhaps the JFrame and JPanel should both be hard coded to the same size.  Or the entire game can be resizable.

**Comment by jalexanderqed** [comment]
F16 CLOSED: The game has been made non-resizeable
