### ISSUE TITLE
Add sound effects/music

### ISSUE THREAD

**Issue by mliou** [ucsb-cs56-projects/cs56-games-country-runner#25]
Have background music play. Maybe add sound effects for jumping, collisions, enemies, etc. 

~ estimated 250 pts

**Comment by jalexanderqed** [comment]
F16 UPDATE: Background music has been added, but sound effects for jumping, collisions, and enemies would be nice additions.

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)

**Comment by Sierrasch** [comment]
W18 OK (150 pts)

**Comment by Sierrasch** [comment]
Done W18
