### ISSUE TITLE
Revamp hit detection

### ISSUE THREAD

**Issue by salolivares** [UCSB-CS56-Projects/cs56-games-country-runner#28]
Right now the game only properly supports one 'enemy' and hit detection for other 'enemies' does not work. A revamp of the hit detection function is necessary to have multiply enemies. 

Relevant file - CountryRunnerJPanel.java: runnerHasCollided();

Point est. 250

**Comment by mliou** [comment]
Approved.

**Comment by jalexanderqed** [comment]
F16 CLOSED: Hit detection now covers all character types.
