### ISSUE TITLE
Modify "Choose Background"

### ISSUE THREAD

**Issue by kyokotake** [UCSB-CS56-Projects/cs56-games-country-runner#45]
Currently the "Choose Background" button, when clicked, changes the background without a notification that the background was changed or what it was changed to. 

Goal: When "Choose Background" is clicked, give a list of background options and if one of the options is clicked, change the background to the selected background.

**Comment by ethanyuwang** [comment]
100 pts request

**Comment by ntpincus** [comment]
100 pts ok

**Comment by jalexanderqed** [comment]
F16 CLOSED: A page for choosing the background has been added.
