### ISSUE TITLE
Game playing character boundary

### ISSUE THREAD

**Issue by kyokotake** [UCSB-CS56-Projects/cs56-games-country-runner#48]
Currently when the game is being played, the user can move off screen and avoid obstacles. They can stay off screen forever and continue to gain points. There needs to be a boundary on how far the user can move the character. 

Estimated points: 100pts?

**Comment by ntpincus** [comment]
M16OK

**Comment by jalexanderqed** [comment]
F16 OK (30 pts)

**Comment by jalexanderqed** [comment]
It still appears that I can move offscreen. Could you point me to the code changes that handle this?
