### ISSUE TITLE
Make into a playable game.

### ISSUE THREAD

**Issue by cmmorris** [UCSB-CS56-Projects/cs56-games-country-runner#5]
~depends #7 

Turn this into a playable game.

Compare: http://www.addictinggames.com/action-games/cityjumper.jsp

The points this is worth depend on how the game is reimagined and redesigned.     The point is not to make a "clone" of city jumper, but to reimagine a similar, but different game set in the country.    What's here is a "good start", but not yet a playable game.

As a starting point: right now if the crash method returns true it draws an image to the screen. Instead, adjust the crash method so the timing is correct, and take appropriate actions.

~estimated 300

**Comment by jalexanderqed** [comment]
F16 CLOSED: It is now a playable game.
