### ISSUE TITLE
Refactor obstacle classes

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-games-country-runner#54]
The different obstacles (Raccoon, Panda, etc.) currently exist as separate classes that are almost completely copy-pasted from each other. It should be possible to refactor them into a single class with certain parameters that differ between each one, possibly listed in a properties file. Alternatively, a class could be created that wraps the majority of their functionality, and different obstacles could extend it that contain small amounts of custom (read: non-repeating) code and configurations (speed, etc.).

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)

**Comment by rayouyang** [comment]
Solved.

**Comment by jalexanderqed** [comment]
It looks like you factored out many of the correct methods, but the `updateCurrentPosition` method still seems to be the same between all of the obstacle classes. Would it be possible to move it into the `Obstacle` class?
