### ISSUE TITLE
Add a death screen/animation

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-games-country-runner#59]
Currently, when a collision occurs, the game screen suddenly changes to the "Your Score/Restart" screen. For this issue, add some sort of death animation and/or game over message. To get started, look at line 228 of `CountryRunnerJPanel.java`

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)

**Comment by jalexanderqed** [comment]
The new death animation is nice, but I noticed that all of the obstacles on the screen disappear when the player dies. Would it be possible to have them stay onscreen?

**Comment by UCSBWillHuang1997** [comment]
I shall implement that!
