### ISSUE TITLE
Refactor to properly handle image display and build jar file

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-games-country-runner#7]
(1) The images should be put into a resources subdirectory, and then read from the classpath. 

(2) The build.xml so that it has a jar target that creates a dist subdirectory and puts a jar file under that subdirectory.     Adjust the jar target so that the images are loaded into the jar in a way that the game can be run from the jar only, even in a different directory.

(3) Add a target "run-from-jar" that tests running the program from the resulting jar file.

(4) Test downloading the jar separately and running it (on a computer with Java, but without the rest of the directory hierarchy.)

**Comment by jalexanderqed** [comment]
F16 CLOSED: jar file generation is currently broken, but a new issue has been created (#53)
