### ISSUE TITLE
Bullet Timing

### ISSUE THREAD

**Issue by UCSBWillHuang1997** [UCSB-CS56-Projects/cs56-games-country-runner#72]
If the bullet interval is decreased from 2000 milliseconds, the shoot function becomes bugged and the image of one of the bullets will kind of latch upon the other bullet. Look at the Runner.java class and CountryRunnerJPanel.java class to fix it.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)

**Comment by joelbagan** [comment]
Resolved in [Pull Request #83](https://github.com/UCSB-CS56-Projects/cs56-games-country-runner/pull/83)
