### ISSUE TITLE
Flying obstacles

### ISSUE THREAD

**Issue by UCSBWillHuang1997** [UCSB-CS56-Projects/cs56-games-country-runner#74]
Flying obstacles will add variety in the game and makes the game harder because the runner's jumping feature becomes negated to some degree. Some flying obstacle examples include a crow or a flygon in pokemon or who knows? USE YOUR CREATIVITY :)

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)

**Comment by joelbagan** [comment]
Resolved in [Pull Request #83](https://github.com/UCSB-CS56-Projects/cs56-games-country-runner/pull/83)
