### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by UCSBWillHuang1997** [ucsb-cs56-projects/cs56-games-country-runner#75]
Portals will float through the screen and if the runner touches the portal, they teleport to a new background with a new character but with the same score. 
Here's a cool picture of a portal: http://vignette4.wikia.nocookie.net/kirby-bulborb/images/1/12/Blue_Portal.png/revision/latest?cb=20151004085207

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)

**Comment by Sierrasch** [comment]
W18 OK (200 pts)

**Comment by Sierrasch** [comment]
Portals implemented W18, but still glitchy. After a few levels, the player will die if they hit a portal. Probably 50-100 points to clean this up and get it working fully.
