### ISSUE TITLE
lowering difficulty

### ISSUE THREAD

**Issue by annahlee** [ucsb-cs56-projects/cs56-games-country-runner#82]
It's pretty much impossible at this point to get very far (because the obstacles bunch up, and we added a flying obstacle) so it would be nice to lower the difficulty by shortening the time interval of bullet firing, adding some space between each of the obstacles, and implementing another way to avoid the obstacles.

**Comment by joelbagan** [comment]
Consider setting limits on the number of obstacles that are allowed to be on the screen at any time. Futher, consider having set intervals for obstacle spawning. Having these variables will allow you to easily tweak the "balance" of the game.

F17 OK (100pts)

**Comment by Sierrasch** [comment]
All of these are good ideas. This one is really open ended so play the game a few times and rebalance it in whatever ways you think would make the game better. See above for ideas. 

W18 OK (100 pts)

**Comment by Sierrasch** [comment]
Done W18
