### ISSUE TITLE
import .sun.audio not supported

### ISSUE THREAD

**Issue by kifung** [ucsb-cs56-projects/cs56-games-country-runner#92]
The current import .sun.audio is not supported in newer versions of Java. The code will not compile in newer versions of Java unless all of the related audio/music code is commented out. We can either delete all of the .sun.audio code or create a new way to provide music in the game.

**Comment by Sierrasch** [comment]
Either find a new music library to use or use an updated version of this library so that music is supported on CSIL and mac, etc... 

W18 OK (125 points)

**Comment by Sierrasch** [comment]
Done W18
